version: "3.8"
services:
  test-app:
    container_name: template-parthos-test-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - test-db
    env_file:
      - .env
    command: >
      sh -c "
      npm install &&
      npm run test &&
      npm run test:e2e &&
      npm run test:cov
      "
    networks:
      - parthos-network
      
  test-db:
    image: postgres:14-alpine
    container_name: parthos-user-test-db
    ports:
      - "5433:5432" # Porta local diferente para não conflitar com o ambiente normal
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - parthos-network

volumes:
  postgres-test-data:
  
networks:
  parthos-network:
    driver: bridge
